---

# Don't touch this file

- name: include global vars file if present
  import_tasks: include-vars.yml

- name: "include tasks"
  include_tasks: "include-file.yml"
  loop_control:
    loop_var: include_file_name 
  with_lines: ls -1 {{ role_path }}/tasks/*/* | egrep '[0-9]{2}_.*\.yml' | sort -nu

...