---
- name: Install MongoDB
  dnf:
    name: "{{ graylog_packages_mongodb }}" 
    state: installed

- name: Enable and start mongod
  service:
    name: mongod
    state: started
    enabled: yes
...
