---
# Add all dependent roles, that should be executed after
# the content of this role. 

- name: uniqconsulting.nginx
  include_role:
    name: uniqconsulting.nginx
  vars:
    nginx_vhosts:
    - default: yes
      type: proxy
      server_name: "{{ [graylog_hostname] + ["graylog.*", "syslog.*"] }}""
      locations:
      - path: /
        pass: https://127.0.0.1:9000
        custom_options:
        - "proxy_set_header X-Graylog-Server-URL https://$server_name/"
      
...