---
# Add all dependent roles, that should be executed before
# the content of this role. If this is an appliance
# there should always be atleast these 3 includes

# Change needed roles here
- name: download dependencies from galaxy
  shell: ansible-galaxy install uniqconsulting.os_basic uniqconsulting.open_vm_tools uniqconsulting.firewall uniqconsulting.nginx uniqconsulting.elasticsearch

# Include all roles like this:

- name: uniqconsulting.os_basic
  include_role:
    name: uniqconsulting.os_basic
  vars:
    setup_selinux: true
    selinux_policy: disabled
    setup_firewalld: false
    setup_iptables: true
    os_update: true
    package_cleanup: true
    package_upgrade: all
    epel_repo: true

- name: uniqconsulting.open_vm_tools
  include_role:
    name: uniqconsulting.open_vm_tools
  when: install_openvmtools
      
- name: uniqconsulting.firewall
  include_role:
    name: uniqconsulting.firewall
  vars:
    firewall_open_ports: "{{ role_ports + additional_open_ports }}"
    firewall_local_port_forwarding: "{{ graylog_firewall_port_forwards }}"

- name: uniqconsulting.elasticsearch
  include_role:
    name: uniqconsulting.elasticsearch
  vars:
    elasticsearch_cluster_name: "{{ graylog_cluster_name }}"

...