---
- name: Install EPEL Release
  dnf:
    name: epel-release

- name: Install Graylog Repositry
  dnf:
    name: "{{ graylog_repo_graylog_rpm }}"
    disable_gpg_check: true

- name: Configure stable MongoDB repo
  template:
    src: mongodb-org.repo.j2
    dest: /etc/yum.repos.d/mongodb-org.repo
    owner: root
    group: root
    mode: 0644
...
