---
  
# Copy & Register uQcCheck
- name: Copy uQcCheck File
  local_action: 
    module: copy
    src: tests/uQcCheck_graylog.yml
    dest: "{{ playbook_dir }}/uQcCheck/uQcCheck_graylog.yml"
  ignore_errors: yes
  tags:
  - graylog
  - installation

- name: Register uQcCheck File
  local_action: 
    module: lineinfile
    line: "- import_playbook: uQcCheck/uQcCheck_graylog.yml"
    path: "{{ playbook_dir }}/task_99_uQcCheck.yml"
  ignore_errors: yes
  tags:
  - graylog
  - installation
  
...